### ISSUE TITLE
Unable to debug .dll files when the plugin is installed

### ISSUE THREAD

**Issue by prolium** [horsicq/pex64dbg#4]
Hello, I can't debug any .dll file if the plugin is installed. the breakpoint at the EntryPoint is never reached, also I tried activating the option to break on DLL load in the debugger but it didn't help.

There's no crash or anything similar, so I can't provide a crash dump or any more helpful info, sorry about that.

**Comment by horsicq** [comment]
Thanks a lot for bugreport.  I' ll take a look. BTW It is very interesting.
